name: pattern_mobx
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  logger: ^1.1.0
  flutter_slidable: ^1.2.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
    # for build => flutter packages pub run build_runner build --delete-conflicting-outputs
  build_runner: ^2.1.8
  mobx_codegen: ^2.0.5+2
  flutter_lints: ^1.0.0



flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
